import { FamilyMember, Relationship, Comment } from './types';

// 4-generation Indian family (~20 members)
export const mockMembers: FamilyMember[] = [
  // Generation 0 - Great-grandparents
  {
    id: 'gg1',
    name: 'Raghunath Sharma',
    gender: 'male',
    dateOfBirth: '1930-03-15',
    dateOfDeath: '2005-08-20',
    location: 'Jaipur, Rajasthan',
    bio: 'Retired school headmaster. Known for his love of classical music and poetry.',
    generation: 0,
  },
  {
    id: 'gg2',
    name: 'Kamla Devi Sharma',
    gender: 'female',
    dateOfBirth: '1935-07-22',
    dateOfDeath: '2010-01-05',
    location: 'Jaipur, Rajasthan',
    bio: 'Homemaker and expert cook. Her dal baati recipe was legendary.',
    generation: 0,
    maidenName: 'Gupta',
  },

  // Generation 1 - Grandparents
  {
    id: 'g1',
    name: 'Vijay Sharma',
    gender: 'male',
    dateOfBirth: '1955-11-10',
    dateOfDeath: '2020-04-12',
    phone: '+91-9876543210',
    location: 'Delhi',
    bio: 'Government engineer who built bridges across Rajasthan. Loved cricket.',
    generation: 1,
  },
  {
    id: 'g2',
    name: 'Sushila Sharma',
    gender: 'female',
    dateOfBirth: '1958-02-14',
    phone: '+91-9876543211',
    email: 'sushila.sharma@email.com',
    location: 'Delhi',
    bio: 'Retired teacher. Runs a small NGO for girl education.',
    generation: 1,
    maidenName: 'Joshi',
  },
  {
    id: 'g3',
    name: 'Prakash Sharma',
    gender: 'male',
    dateOfBirth: '1957-06-30',
    phone: '+91-9876543212',
    location: 'Mumbai',
    bio: 'Businessman. Runs a textile export company.',
    generation: 1,
  },
  {
    id: 'g4',
    name: 'Meena Sharma',
    gender: 'female',
    dateOfBirth: '1960-09-05',
    phone: '+91-9876543213',
    location: 'Mumbai',
    bio: 'Interior designer and artist.',
    generation: 1,
    maidenName: 'Verma',
  },

  // Generation 2 - Parents
  {
    id: 'p1',
    name: 'Amit Sharma',
    gender: 'male',
    dateOfBirth: '1980-04-25',
    phone: '+91-9876543214',
    email: 'amit.sharma@email.com',
    location: 'Bangalore',
    bio: 'Software architect at a leading tech company. Passionate about open source.',
    generation: 2,
  },
  {
    id: 'p2',
    name: 'Priya Sharma',
    gender: 'female',
    dateOfBirth: '1983-12-18',
    phone: '+91-9876543215',
    email: 'priya.sharma@email.com',
    location: 'Bangalore',
    bio: 'Pediatrician. Volunteers at a community clinic on weekends.',
    generation: 2,
    maidenName: 'Reddy',
  },
  {
    id: 'p3',
    name: 'Neha Sharma',
    gender: 'female',
    dateOfBirth: '1982-08-03',
    phone: '+91-9876543216',
    email: 'neha.kapoor@email.com',
    location: 'Delhi',
    bio: 'Journalist covering politics. Award-winning reporter.',
    generation: 2,
  },
  {
    id: 'p4',
    name: 'Rahul Kapoor',
    gender: 'male',
    dateOfBirth: '1981-01-20',
    phone: '+91-9876543217',
    email: 'rahul.kapoor@email.com',
    location: 'Delhi',
    bio: 'Civil servant in the IAS. Currently posted in Delhi.',
    generation: 2,
  },
  {
    id: 'p5',
    name: 'Vikram Sharma',
    gender: 'male',
    dateOfBirth: '1984-05-12',
    phone: '+91-9876543218',
    email: 'vikram.sharma@email.com',
    location: 'Pune',
    bio: 'Runs a chain of organic food stores.',
    generation: 2,
  },
  {
    id: 'p6',
    name: 'Anita Sharma',
    gender: 'female',
    dateOfBirth: '1986-10-30',
    phone: '+91-9876543219',
    email: 'anita.sharma@email.com',
    location: 'Pune',
    bio: 'Yoga instructor and wellness coach.',
    generation: 2,
    maidenName: 'Desai',
  },
  {
    id: 'p7',
    name: 'Sunita Sharma',
    gender: 'female',
    dateOfBirth: '1985-03-22',
    phone: '+91-9876543220',
    email: 'sunita.mehta@email.com',
    location: 'Hyderabad',
    bio: 'Architect specializing in sustainable buildings.',
    generation: 2,
  },
  {
    id: 'p8',
    name: 'Rajesh Mehta',
    gender: 'male',
    dateOfBirth: '1983-07-15',
    phone: '+91-9876543221',
    email: 'rajesh.mehta@email.com',
    location: 'Hyderabad',
    bio: 'Professor of Computer Science at IIIT Hyderabad.',
    generation: 2,
  },

  // Generation 3 - Children
  {
    id: 'c1',
    name: 'Arjun Sharma',
    gender: 'male',
    dateOfBirth: '2008-09-15',
    location: 'Bangalore',
    bio: 'Student. Loves robotics and chess.',
    generation: 3,
  },
  {
    id: 'c2',
    name: 'Aanya Sharma',
    gender: 'female',
    dateOfBirth: '2011-03-28',
    location: 'Bangalore',
    bio: 'Student. Bharatanatyam dancer and bookworm.',
    generation: 3,
  },
  {
    id: 'c3',
    name: 'Kabir Kapoor',
    gender: 'male',
    dateOfBirth: '2010-06-10',
    location: 'Delhi',
    bio: 'Student. Cricket enthusiast, plays for school team.',
    generation: 3,
  },
  {
    id: 'c4',
    name: 'Ishaan Sharma',
    gender: 'male',
    dateOfBirth: '2012-12-01',
    location: 'Pune',
    bio: 'Student. Loves painting and swimming.',
    generation: 3,
  },
  {
    id: 'c5',
    name: 'Riya Mehta',
    gender: 'female',
    dateOfBirth: '2013-04-18',
    location: 'Hyderabad',
    bio: 'Student. Aspiring astronaut and science lover.',
    generation: 3,
  },
  {
    id: 'c6',
    name: 'Advait Mehta',
    gender: 'male',
    dateOfBirth: '2016-08-25',
    location: 'Hyderabad',
    bio: 'Kindergartener. Loves dinosaurs.',
    generation: 3,
  },
];

export const mockRelationships: Relationship[] = [
  // Great-grandparents are spouses
  { id: 'r1', type: 'spouse', fromMemberId: 'gg1', toMemberId: 'gg2' },

  // Great-grandparents -> Grandparents (parent relationships)
  { id: 'r2', type: 'parent', fromMemberId: 'gg1', toMemberId: 'g1' },
  { id: 'r3', type: 'parent', fromMemberId: 'gg2', toMemberId: 'g1' },
  { id: 'r4', type: 'parent', fromMemberId: 'gg1', toMemberId: 'g3' },
  { id: 'r5', type: 'parent', fromMemberId: 'gg2', toMemberId: 'g3' },

  // Grandparent spouses
  { id: 'r6', type: 'spouse', fromMemberId: 'g1', toMemberId: 'g2' },
  { id: 'r7', type: 'spouse', fromMemberId: 'g3', toMemberId: 'g4' },

  // Grandparents -> Parents
  { id: 'r8', type: 'parent', fromMemberId: 'g1', toMemberId: 'p1' },
  { id: 'r9', type: 'parent', fromMemberId: 'g2', toMemberId: 'p1' },
  { id: 'r10', type: 'parent', fromMemberId: 'g1', toMemberId: 'p3' },
  { id: 'r11', type: 'parent', fromMemberId: 'g2', toMemberId: 'p3' },
  { id: 'r12', type: 'parent', fromMemberId: 'g3', toMemberId: 'p5' },
  { id: 'r13', type: 'parent', fromMemberId: 'g4', toMemberId: 'p5' },
  { id: 'r14', type: 'parent', fromMemberId: 'g3', toMemberId: 'p7' },
  { id: 'r15', type: 'parent', fromMemberId: 'g4', toMemberId: 'p7' },

  // Parent spouses
  { id: 'r16', type: 'spouse', fromMemberId: 'p1', toMemberId: 'p2' },
  { id: 'r17', type: 'spouse', fromMemberId: 'p3', toMemberId: 'p4' },
  { id: 'r18', type: 'spouse', fromMemberId: 'p5', toMemberId: 'p6' },
  { id: 'r19', type: 'spouse', fromMemberId: 'p7', toMemberId: 'p8' },

  // Parents -> Children
  { id: 'r20', type: 'parent', fromMemberId: 'p1', toMemberId: 'c1' },
  { id: 'r21', type: 'parent', fromMemberId: 'p2', toMemberId: 'c1' },
  { id: 'r22', type: 'parent', fromMemberId: 'p1', toMemberId: 'c2' },
  { id: 'r23', type: 'parent', fromMemberId: 'p2', toMemberId: 'c2' },
  { id: 'r24', type: 'parent', fromMemberId: 'p3', toMemberId: 'c3' },
  { id: 'r25', type: 'parent', fromMemberId: 'p4', toMemberId: 'c3' },
  { id: 'r26', type: 'parent', fromMemberId: 'p5', toMemberId: 'c4' },
  { id: 'r27', type: 'parent', fromMemberId: 'p6', toMemberId: 'c4' },
  { id: 'r28', type: 'parent', fromMemberId: 'p7', toMemberId: 'c5' },
  { id: 'r29', type: 'parent', fromMemberId: 'p8', toMemberId: 'c5' },
  { id: 'r30', type: 'parent', fromMemberId: 'p7', toMemberId: 'c6' },
  { id: 'r31', type: 'parent', fromMemberId: 'p8', toMemberId: 'c6' },

  // Siblings
  { id: 'r32', type: 'sibling', fromMemberId: 'g1', toMemberId: 'g3' },
  { id: 'r33', type: 'sibling', fromMemberId: 'p1', toMemberId: 'p3' },
  { id: 'r34', type: 'sibling', fromMemberId: 'p5', toMemberId: 'p7' },
  { id: 'r35', type: 'sibling', fromMemberId: 'c1', toMemberId: 'c2' },
  { id: 'r36', type: 'sibling', fromMemberId: 'c5', toMemberId: 'c6' },
];

export const mockComments: Comment[] = [
  {
    id: 'cm1',
    memberId: 'gg1',
    authorName: 'Amit Sharma',
    text: 'Dadaji always told the best stories about independence. Miss him every day.',
    type: 'memory',
    createdAt: '2024-08-20T10:00:00Z',
  },
  {
    id: 'cm2',
    memberId: 'g2',
    authorName: 'Priya Sharma',
    text: 'Happy birthday Mummy ji! Wishing you good health and happiness always.',
    type: 'birthday',
    createdAt: '2025-02-14T08:00:00Z',
  },
  {
    id: 'cm3',
    memberId: 'c1',
    authorName: 'Vijay Sharma',
    text: 'So proud of Arjun for winning the robotics competition!',
    type: 'general',
    createdAt: '2025-01-15T14:30:00Z',
  },
  {
    id: 'cm4',
    memberId: 'gg2',
    authorName: 'Neha Sharma',
    text: 'Dadiji, your dal baati recipe lives on. We make it every Sunday.',
    type: 'memory',
    createdAt: '2024-01-05T12:00:00Z',
  },
  {
    id: 'cm5',
    memberId: 'g1',
    authorName: 'Amit Sharma',
    text: 'Papa, we miss you terribly. Your bridge designs still stand strong.',
    type: 'condolence',
    createdAt: '2024-04-12T09:00:00Z',
  },
];
